### ISSUE TITLE
A more elaborate example

### ISSUE THREAD

**Issue by iszczesniak** [GaelGirodon/yaml-to-docx#1]
Hi,

Could you please provide a more elaborate example?  How exactly is the yaml processed?  How is it mapped into the values in the docx document?  Can I write something like ${name.somearray[0]}?

Thanks!

**Comment by GaelGirodon** [comment]
Hello,

Thanks for opening this issue.

Basically, **YAML → Docx** is only a simple wrapper (providing a CLI and support for a YAML file input) around a subset of the `.docx` file modification features of PHPWord.

As you can see in the [source code](https://github.com/GaelGirodon/yaml-to-docx/blob/master/src/YamlToDocxGenerator.php#L77), the tool takes all variables defined in the YAML file and sets each value in the template ([setValue](https://phpword.readthedocs.io/en/latest/templates-processing.html#setvalue)). If the value is an array, it uses the [cloneRow](https://phpword.readthedocs.io/en/latest/templates-processing.html#clonerow) feature to duplicate the table row template.

As it is done right now, you won't be able to write something like `${name.somearray[0]}`. You can only use basic variables (`key` => `value`) and simple arrays.

The example on the `README.md` shows pretty much everything of what this tool can do. I must admit that this is basic but it matched my needs when I published it (automate the generation of delivery forms).

If you need to use most advanced features, you can use directly PHPWord. This library is very powerful yet simple to use.

**Comment by iszczesniak** [comment]
Hi,

Thank you for the explanation!


Best,
Irek
